app:

    logDir: "logs"
    lumberJackLogging:
        filename:   "logs/notify-eft/eft.log"
        maxSize:    500
        maxBackups: 3
        maxAge:     28
        compress: true

fileProcessor:
    globPath: "AP566*"
    olderThanSeconds: 2
    inputDir : "/Volumes/data01/projects/projects_go/go-mail/input/"
    doneDir  : "/Volumes/data01/projects/projects_go/go-mail/done/"
    errorDir : "/Volumes/data01/projects/projects_go/go-mail/error/"
#    inputDir : "C:\\data\\projects\\projects_go\\go-mail\\input\\"
#    doneDir  : "C:\\data\\projects\\projects_go\\go-mail\\done\\"
#    errorDir : "C:\\data\\projects\\projects_go\\go-mail\\error\\"

# fake-smtp-server
#mailServer:
#     host: "0.0.0.0"
#     port: 1025
#     ccUser: "finance-noreply@gmail.com"
#     opsUser: "appsalert@google.com"
#     user: ""
#     password: ""
# mk
mailServer:
    host: "mailext.markhamcity.ca"
    port: 25
    ccUser: "finance-noreply@gmail.com"
    opsUser: "appsalert@google.com"
    user: ""
    password: ""

#gmail 
# mailserver:
#     host: "smtp.gmail.com"
#     port: 465
#     user: "@gmail.com"
#     password: ""
