# fake-smtp-server
mailserver:
    host: "0.0.0.0"
    port: 1025
    user: "me@gmail.com"
    password: ""
#gmail 
# mailserver:
#     host: "smtp.gmail.com"
#     port: 465
#     user: "pad.@gmail.com"
#     password: ""
fileFilterConfig:
    globPath: "/Volumes/data01/projects/projects_go/go-mail/inputfile*"
    olderThanSeconds: 2
