app:

    lumberJackLogging:
        filename:   "logs/notify-eft/eft.log"
        maxSize:    500
        maxBackups: 3
        maxAge:     28
        compress: true

fileProcessor:
    globPath: "AP566*"
    olderThanSeconds: 2
    inputDir: "C:\\data\\temp\\go-mail\\input\\"
    doneDir: "C:\\data\\temp\\go-mail\\done\\"
    errorDir: "C:\\data\\temp\\go-mail\\error\\"

# fake-smtp-server
mailServer:
    host: "0.0.0.0"
    port: 1025
    ccUser: "finance-noreply@gmail.com"
    opsUser: "appsalert@google.com"
    user: ""
    password: ""

#gmail 
# mailserver:
#     host: "smtp.gmail.com"
#     port: 465
#     user: "@gmail.com"
#     password: ""
